name: dart_playground
version: 0.0.1
description: Example of Styling Material UI Components to look like Web Skin Dart components

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  over_react: ^4.0.0
  react: ^6.0.0
  meta: '<1.7.0'

dev_dependencies:
  build_runner: ">1.0.0 <1.11.2"
  build_test: ">=0.10.9 <2.0.0"
  build_web_compilers: ^2.0.0
  react_testing_library: ^2.0.0
  test: ^1.15.7
  test_html_builder: ^2.2.2
