name: dart_playground
version: 0.0.1
description: Playground with Unify and RTL

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  over_react: ^4.0.0
  react: ^6.0.0
  react_material_ui:
    hosted:
      name: react_material_ui
      url: https://pub.workiva.org
    version: ^1.106.0
  web_skin_dart:
    hosted:
      name: web_skin_dart
      url: https://pub.workiva.org
    version: any
  web_skin:
    hosted:
      name: web_skin
      url: https://pub.workiva.org
    version: any
  meta: '<1.7.0'

dev_dependencies:
  build_runner: '>=1.7.1 <3.0.0'
  build_test: '>=1.0.0 <3.0.0'
  build_web_compilers: '>=2.6.1 <4.0.0'
  react_testing_library: ^2.0.0
  test: ^1.9.1
  test_html_builder: '>=2.2.2 <4.0.0'
  over_react_format:
    hosted:
      name: over_react_format
      url: https://pub.workiva.org
    version: ^3.1.0
