name: dart_playground
version: 0.0.1
description: Example of Styling Material UI Components to look like Web Skin Dart components

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  over_react: ^4.0.0
  react: ^6.0.0
  react_material_ui:
    hosted:
      name: react_material_ui
      url: https://pub.workiva.org
    version: ^1.17.5
  web_skin_dart:
    hosted:
      name: web_skin_dart
      url: https://pub.workiva.org
    version: any
  web-skin:
    hosted:
      name: web-skin
      url: https://pub.workiva.org
    version: any
  meta: '<1.7.0'

dev_dependencies:
  build_runner: ">1.0.0 <1.11.2"
  build_test: ">=0.10.9 <2.0.0"
  build_web_compilers: ^2.0.0
  react_testing_library: ^2.0.0
  test: ^1.15.7
  test_html_builder: ^2.2.2

dependency_overrides:
  react_material_ui:
    git:
      url: git@github.com:Workiva/react_material_ui.git
      ref: export-grid-dev-branch
